import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
x=np.array([[1,2],[2,1],[3,4],[4,3],[5,5],[6,7],[7,6],[8,8]])
y=np.array([3,3,7,7,10,13,13,16]).reshape(-1,1)
ones=np.ones((x.shape[0],1))
x_b=np.hstack((ones,x))
theta=np.linalg.inv(x_b.T.dot(x_b)).dot(x_b.T).dot(y)
print("parameter(theta):")
print(theta)
y_pred=x_b.dot(theta)
n=len(y)
mse=np.sum(((y-y_pred)**2)/n)
print("MEAN SQUARE ROOT:",mse)
mean_y=np.mean(y)
ss_res=np.sum((y-y_pred)**2)
ss_tot=np.sum((y-mean_y)**2)
r2=1-(ss_res/ss_tot)
print("R-SQUARED:",r2)
plt.scatter(y,y_pred)
plt.plot([min(y),max(y)],[min(y),max(y)])
plt.xlabel("actual values")
plt.ylabel("predicted values")
plt.title("actual vs predicted (mutltiple linear regression)")
plt.show()

